#!/usr/bin/env bash
set -euo pipefail

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly REPOSITORY_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
readonly CONFIG_DIR="$REPOSITORY_ROOT/.codex/skills/testflight-feedback/config"

mkdir -p "$CONFIG_DIR"

for example in settings.json allowed-emails.json baseline.json handled-feedback.json; do
  target="$CONFIG_DIR/$example"
  source="$CONFIG_DIR/$example.example"
  if [[ -e "$target" ]]; then
    echo "exists: $target"
  else
    cp "$source" "$target"
    chmod 600 "$target"
    echo "created: $target"
  fi
done

cat <<'EOF'

Local TestFlight configuration was created under the ignored skill config directory.
Fill in settings.json, allowed-emails.json, and baseline.json, then validate the read-only profile:

  asc auth status --profile '<READ_PROFILE>' --validate

No credential or tester data was generated by this script.
EOF
